<form action="" method="get">
	<input name="keyword" value="">
	<button type="submit">查询</button>
</form>
<ul>
	<?php foreach($artists->items as $item ) { ?>
	<li>
		<?= $item->name ?>
		<a href="<?= $this->url->get('admin/artists/del/'.$item->id) ?>">删除</a>
		<a href="<?= $this->url->get('admin/artists/edit/'.$item->id) ?>">编辑</a>
	</li>
	<?php } ?>
</ul>
<a href="<?= $this->url->get('admin/artists/index') ?>">首页</a>
<a href="<?= $this->url->get('admin/artists/index', ['page' => $artists->before]) ?>">上一页</a>
<a href="<?= $this->url->get('admin/artists/index', ['page' => $artists->next]) ?>">下一页</a>
<a href="<?= $this->url->get('admin/artists/index', ['page' => $artists->last]) ?>">尾页</a>

当前页码：<?= $artists->current, " of ", $artists->total_pages; ?>
